spotigeek/__init__.py
from flask import Flask
from config import get_config
from spotigeek.app.main.views import main
from spotigeek.app.test.views import test

import os
from dotenv import load_dotenv
load_dotenv()

def create_app():
    app = Flask(__name__)
    flask_env = os.environ.get("FLASK_ENV")
    app.config.from_object(get_config(flask_env))
    
    app.register_blueprint(main)
    app.register_blueprint(test, url_prefix='/test')
    return app

spotigeek/app/main/views.py
from flask import Blueprint, redirect, url_for, request, session, render_template, flash, jsonify
from pandas import DataFrame
import os
from dotenv import load_dotenv
from spotipy import SpotifyOAuth, Spotify
from time import sleep, time
import json

from spotigeek.app.main.decorators import auth_required, check_token_expired
from spotigeek.app.main.functions import create_spotify_oauth, get_now_playing

main = Blueprint('main', __name__, template_folder="../../templates/main")

@main.route('/')
@auth_required
@check_token_expired
def index():
    spotify = Spotify(auth=session.get('token_data').get('access_token'))
    now_playing = get_now_playing(spotify).get_json()
    # print(now_playing)
    return render_template("index.html", sidebar=True, now_playing=now_playing)

@main.route('/authorize')
def auth():
    return render_template("auth.html", sidebar=True)

@main.route('/spotify-oauth')
def authorize():
    spotify_oauth = create_spotify_oauth()
    auth_url = spotify_oauth.get_authorize_url()
    return redirect(auth_url)

@main.route('/callback')
def callback():
    spotify_oath = create_spotify_oauth()
    session.clear()
    code = request.args.get('code')
    session['token_data'] = spotify_oath.get_access_token(code)
    return redirect(url_for('main.index', _external=True))

@main.route('/logout')
def logout():
    session.pop('token_data')
    return redirect(url_for('main.auth'))

@main.route('/top')
@auth_required
@check_token_expired
def top():
    spotify = Spotify(auth=session.get('token_data').get('access_token'))
    user_top = spotify.current_user_top_tracks(limit=50, time_range="long_term")
    return {"top": user_top['items']}

@main.route('/now-playing')
@auth_required
@check_token_expired
def now_playing():
    sp = Spotify(auth=session.get('token_data').get('access_token'))
    np = get_now_playing(sp)
    # np = sp.current_user_playing_track()
    # album = sp.album_tracks("3cLQ49Ll3nGRkw3HSSk92K")
    return np

spotigeek/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <!-- Meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <!-- Boxicons CDN -->
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    
    <!-- Stylesheet base CSS -->
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/base.css') }}">
    <!-- Sylesheet if sidebar -->
    {% if sidebar and sidebar==True %}
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/sidebar.css') }}">
    {% endif %}
    <title>Spotigeek</title>

    <!-- Load head -->
    {% block head %}
    {% endblock %}
</head>
<body>
    <!-- Load html if sidebar -->
    {% if sidebar and sidebar==True %}
        {% include "layouts/sidebar.html" %}
    {% endif %}
    
    <main>
        <!-- Load main -->
        {% block main %}
        {% endblock %}
    </main>
    
    <!-- Load script if sidebar -->
    {% if sidebar and sidebar==True%}
        <script src="{{url_for('static', filename='js/sidebar.js')}}"></script>
    {% endif %}
</body>

spotigeek/templates/layouts/sidebar.html
<nav class="sidebar">
    <div class="logo-details">
        <i class='bx bxl-python icon' ></i>
        <div class="logo-name">Spotigeek</div>
        <i class='bx bx-menu' id="btn"></i>
    </div>
    <ul class="nav-list">
        <li>
            <a href="#">
                <i class='bx bx-play-circle' ></i>
                <span class="link-name">Now Playing</span>
            </a>
            <span class="tooltip">Now Playing</span>
        </li>
        <li>
            <a href="#">
                <i class='bx bx-bar-chart' ></i>
                <span class="link-name">Stats</span>
            </a>
            <span class="tooltip">Stats</span>
        </li>
        <li>
            <a href="#">
                <i class='bx bx-cog' ></i>
                <span class="link-name">Settings</span>
            </a>
            <span class="tooltip">Settings</span>
        </li>
        <li class="app-info">
            <div class="app-details">
                <i class='bx bxl-spotify logo'></i>
                <div class="info">
                    <div class="name">Spotigeek</div>
                    <div class="developer">Thomas de Lange</div>
                </div>
            </div>
            <a class="log-out" href="{{ url_for('main.logout') }}">
                <i class='bx bx-log-out' id="log_out" ></i>
            </a>
            <span class="tooltip">Logout</span>
        </li>
    </ul>
</nav>

spotigeek/templates/main/auth.html
<a href="{{ url_for('main.authorize') }}"><button>Authorize</button></a>

spotigeek/templates/main/index.html
{% extends  "layouts/base.html"%}

{% block head %}
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/index.css') }}">
<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
{% endblock %}
{% block main %}
<section id="particles" class="now-playing">
    <div class="container">
        <div class="album-container">
          {% if 'error' not in now_playing %}
            <div class="album">
                <div class="frontside">
                    <img src="{{ now_playing['album_img'] }}">
                </div>
                <div class="backside">
                  <div class="track-details">
                    <h1>Tracks</h1>
                    <ul>
                      {% for number, track in now_playing['album_tracks'].items() %}
                        <li class="track{% if number|string == now_playing['track_number']|string %} current{% endif %}">
                          <span class="name">{{ "%02.f"|format(number|float) }}. {{ track['name'] }}</span>
                          <span class="duration"> - [{{ track['duration'] }}]</span>
                        </li>
                      {% endfor %}
                      </ul>
                  </div>
                  <div class="album-details">
                    <h1 class="name">{{ now_playing['album_name'] }}</h1>
                    <p>{{ now_playing['album_artists'] }} . {{ now_playing['album_release_year'] }}</p>
                  </div>
                </div>
            </div>
          {% else %}
            <h1>Start playing some music!</h1>
          {% endif %}
        </div>
    </div>
</section>
<section>
    <h1>Stats</h1>
</section>
<script>
    particlesJS("particles", {
  "particles": {
    "number": {
      "value": 355,
      "density": {
        "enable": true,
        "value_area": 789.1476416322727
      }
    },
    "color": {
      "value": "#ffffff"
    },
    "shape": {
      "type": "circle",
      "stroke": {
        "width": 0,
        "color": "#000000"
      },
      "polygon": {
        "nb_sides": 5
      },
      "image": {
        "src": "img/github.svg",
        "width": 100,
        "height": 100
      }
    },
    "opacity": {
      "value": 0.48927153781200905,
      "random": false,
      "anim": {
        "enable": true,
        "speed": 0.2,
        "opacity_min": 0,
        "sync": false
      }
    },
    "size": {
      "value": 2,
      "random": true,
      "anim": {
        "enable": true,
        "speed": 2,
        "size_min": 0,
        "sync": false
      }
    },
    "line_linked": {
      "enable": false,
      "distance": 150,
      "color": "#ffffff",
      "opacity": 0.4,
      "width": 1
    },
    "move": {
      "enable": true,
      "speed": 0.2,
      "direction": "none",
      "random": true,
      "straight": false,
      "out_mode": "out",
      "bounce": false,
      "attract": {
        "enable": false,
        "rotateX": 600,
        "rotateY": 1200
      }
    }
  },
  "interactivity": {
    "detect_on": "canvas",
    "events": {
      "onhover": {
        "enable": true,
        "mode": "bubble"
      },
      "onclick": {
        "enable": true,
        "mode": "push"
      },
      "resize": true
    },
    "modes": {
      "grab": {
        "distance": 400,
        "line_linked": {
          "opacity": 1
        }
      },
      "bubble": {
        "distance": 83.91608391608392,
        "size": 1,
        "duration": 3,
        "opacity": 1,
        "speed": 3
      },
      "repulse": {
        "distance": 200,
        "duration": 0.4
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true
});
</script>
{% endblock %}